#!/usr/bin/env sh
echo "Starting function..."
echo "FUNCTIONS_CUSTOMHANDLER_PORT: ${FUNCTIONS_CUSTOMHANDLER_PORT}"
echo "FUNCTIONS_HTTPWORKER_PORT: ${FUNCTIONS_HTTPWORKER_PORT}"
echo "WEBSITES_PORT: ${WEBSITES_PORT}"
FLOGO_APP_PROPS_OVERRIDE="FUNCTIONS_CUSTOMHANDLER_PORT=${FUNCTIONS_CUSTOMHANDLER_PORT}" ./TasksRestServer-linux_amd64